### ISSUE TITLE
Using CROPS:7 for a blocks mission and it won't the wheat when broken?

### ISSUE THREAD

**Issue by Nekosity12** [OmerBenGera/SuperiorSkyblock2#116]
Quest seems to register just fine no errors or anything, just does not recognize the wheat when broken.

https://www.youtube.com/watch?v=uyygJHwhL44
Video of a user breaking wheat
(Sorry if this is just me being an idiot somehow, this is the ID I was given in the discord to make the quest)
Quest in question:
```
wheattingyourappetite:
  mission-file: BlocksMissions
  island: false
  auto-reward: true
  disband-reset: true
  leave-reset: true
  rewards:
    items:
      "1":
        type: DISPENSER
        amount: 1
      "2":
        type: DIRT
        amount: 16
    commands:
      - 'is admin title %player% 25 20 10 -title &e&lCongratulations -subtitle &fYou completed "&aWheatting Your Appetite&f"!'
      - "money give %player% 5000"
  required-blocks:
    "1":
      types:
        - "CROPS:7"
      amount: 16
  reset-after-finish: false
  required-missions:
    - "recycling"
  only-show-if-required-completed: true
  icons:
    not-completed:
      type: WHEAT
      name: "&aWheatting Your Appetite"
      lore:
        - "&7Now that you have some dirt and a way"
        - "&7to make more dirt we need to work on"
        - "&7a food source quickly! Farm 16 wheat"
        - ""
        - "&aTip - Farming wheat a little slow or"
        - "&aboring? Try using a watering can! It"
        - "speeds up growth of saplings or crops!"
        - ""
        - "&6Required Crops Broken:"
        - "&8 - &7x16 Wheat"
        - ""
        - "&6Rewards:"
        - "&8 - &7$5,000"
        - "&8 - &7x16 Dirt"
        - "&8 - &7x1 Dispenser"
        - ""
        - "&6Wheat collected: &7{1}/16"
        - "&6Progress: &7{0}%"
        - "&c&l ✘ &7Not Completed"
    can-complete:
      type: WHEAT
      name: "&aWheatting Your Appetite"
      lore:
        - "&7Now that you have some dirt and a way"
        - "&7to make more dirt we need to work on"
        - "&7a food source quickly! Farm 16 wheat"
        - ""
        - "&aTip - Farming wheat a little slow or"
        - "&aboring? Try using a watering can! It"
        - "speeds up growth of saplings or crops!"
        - ""
        - "&6Required Crops Broken:"
        - "&8 - &7x16 Wheat"
        - ""
        - "&6Rewards:"
        - "&8 - &7$5,000"
        - "&8 - &7x16 Dirt"
        - "&8 - &7x1 Dispenser"
        - ""
        - "&6Wheat collected: &716/16"
        - "&6Progress: &7100%"
        - "&a&l ✔ &7Click to redeem your reward."
      enchants:
        DURABILITY: 1
      flags:
        - HIDE_ENCHANTS
    completed:
      type: MAP
      name: "&aWheatting Your Appetite"
      lore:
        - "&7Now that you have some dirt and a way"
        - "&7to make more dirt we need to work on"
        - "&7a food source quickly! Farm 16 wheat"
        - ""
        - "&6Wheat collected: &716/16"
        - "&6Progress: &7100%"
        - "&a&l ✔ &7Already Claimed."
```
