### ISSUE TITLE
Error upon trying to submit a quest

### ISSUE THREAD

**Issue by Nekosity12** [OmerBenGera/SuperiorSkyblock2#128]
**Minecraft's Version**
_The minecraft version your server run on. Use /version to find which version you use.
It's recommended to also mention which jar you use (Spigot, Paper, etc)_
V1.16.5
Running Purpur
**Plugin's Version**: -
_The version of the plugin. If you use a dev build, mention which dev build you use._
v1.5.2-DEVb101
**Describe the bug**
_A clear and concise description of what the bug is._
When a specific quest is completed an error pops up in console. This is with a custom slimefun mission jar. Only seems to be this one specific mission and nothing is really changed with the other two. It also consumes one of the requirements but not the other. This is semi-fixed if I use auto-reward, it will take the first requirement then when you have the requirements again it will take all of them and complete it whereas you just can't complete it at all with auto-reward off.
Error:
```
[02:58:14 WARN]: [SuperiorSkyblock2] Plugin SuperiorSkyblock2 v1.5.2 generated an exception while executing task 17283692
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.nextNode(HashMap.java:1493) ~[?:?]
        at java.util.HashMap$KeyIterator.next(HashMap.java:1516) ~[?:?]
        at io.ncbpfluffybear.slimefunitemmission.SlimefunItemMission.onComplete(SlimefunItemMission.java:156) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.MissionsHandler.rewardMission(MissionsHandler.java:296) ~[?:?]
        at com.bgsoftware.superiorskyblock.handlers.MissionsHandler.lambda$rewardMission$6(MissionsHandler.java:226) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.5.jar:git-Purpur-1001]
        at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58) ~[patched_1.16.5.jar:git-Purpur-1001]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.5.jar:git-Purpur-1001]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
**To Reproduce**
_Steps to reproduce the bug._
Would need the slimefun jar, karma jar and slimefun jar to reproduce this, then just finish the quest (Quest information will be provided in additional information) If you need anything let us know.

**Additional information**
_Additional information that can help understanding the issue.
Config file, clips, etc are more than welcome._
For good measure going to also attach a file with the other 2 karma quests which don't seem to have an issue.
[karma missions.txt](https://github.com/OmerBenGera/SuperiorSkyblock2/files/6181018/karma.missions.txt)
```
no!karmavsluck!!:
  mission-file: SlimefunItemMission
  island: false
  auto-reward: false
  disband-reset: true
  leave-reset: true
  consume-items: true
  rewards:
    commands:
      - 'is admin title %player% 25 20 10 -title &e&lCongratulations -subtitle &fYou completed "&aNo! Karma vs Luck!!&f"!'
      - "money give %player% 1000"
      - 'give %player% paper{display:{Name:"\"&dI finished a quest and all I got was this dumb paper and $1,000\"",Lore:["\"\"","\"&bWith Great Love\"","\"&b&l-Neko\""]},Enchantments:[{id:unbreaking,lvl:1}]}'
  required-items:
    "1":
      slimefunid: "KARMA_SMALL_PURE"
      amount: 15
    "2":
      slimefunid: "KARMA_SMALL_CORRUPT"
      amount: 15
  reset-after-finish: false
  required-missions:
    - "luckvskarma?"
  only-show-if-required-completed: true
  icons:
    not-completed:
      type: DRAGON_EGG
      name: "&aNo! Karma vs Luck!!"
      lore:
        - "&7Good job! Now you might have noticed a bigger karma dropping"
        - "&7or have been thinking what the hell this is an absurdly small"
        - "&7amount of karma. Well don't worry you can kill other mobs for"
        - "&7even larger karma! Killing spiders & creepers nets you small"
        - "&7karma that gets you 9 karma per crystal. Be sure to grind lots"
        - "&7in order to get the awesome perks the ranks offer you! (Or if"
        - "&7you think they aren't awesome then suggest changes on the"
        - "&7discord and we may very well implement your suggestion!!!)"
        - ""
        - "&6Required Materials:"
        - "&8 - &7x15 Small Corrupt Karma"
        - "&8 - &7x15 Small Pure Karma"
        - ""
        - "&6Rewards:"
        - "&8 - &7A Secret Surprise"
        - "&8 - &7$1,000"
        - ""
        - "&6Progress: &7{0}%"
        - "&c&l ✘ &7Not Completed"
    can-complete:
      type: DRAGON_EGG
      name: "&aNo! Karma vs Luck!!"
      lore:
        - "&7Good job! Now you might have noticed a bigger karma dropping"
        - "&7or have been thinking what the hell this is an absurdly small"
        - "&7amount of karma. Well don't worry you can kill other mobs for"
        - "&7even larger karma! Killing spiders & creepers nets you small"
        - "&7karma that gets you 9 karma per crystal. Be sure to grind lots"
        - "&7in order to get the awesome perks the ranks offer you! (Or if"
        - "&7you think they aren't awesome then suggest changes on the"
        - "&7discord and we may very well implement your suggestion!!!)"
        - ""
        - "&6Required Materials:"
        - "&8 - &7x15 Small Corrupt Karma"
        - "&8 - &7x15 Small Pure Karma"
        - ""
        - "&6Rewards:"
        - "&8 - &7A Secret Surprise"
        - "&8 - &7$1,000"
        - ""
        - "&6Progress: &7100%"
        - "&a&l ✔ &7Click to redeem your reward."
      enchants:
        DURABILITY: 1
      flags:
        - HIDE_ENCHANTS
    completed:
      type: MAP
      name: "&aNo! Karma vs Luck!!"
      lore:
        - "&7Good job! Now you might have noticed a bigger karma dropping"
        - "&7or have been thinking what the hell this is an absurdly small"
        - "&7amount of karma. Well don't worry you can kill other mobs for"
        - "&7even larger karma! Killing spiders & creepers nets you small"
        - "&7karma that gets you 9 karma per crystal. Be sure to grind lots"
        - "&7in order to get the awesome perks the ranks offer you! (Or if"
        - "&7you think they aren't awesome then suggest changes on the"
        - "&7discord and we may very well implement your suggestion!!!)"
        - ""
        - "&6Progress: &7100%"
        - "&a&l ✔ &7Already Claimed."
```
