### ISSUE TITLE
Island level problem

### ISSUE THREAD

**Issue by J4im3x0** [OmerBenGera/SuperiorSkyblock2#41]
Hello,

I have 2 issues. 
1. When I delete my island, my previous level still appearing on %superior_island_total_level%
![image](https://user-images.githubusercontent.com/36940599/105644993-a78bac80-5e77-11eb-8483-1f0ba1c31c8a.png)

2. When I create a new island the placeholder %superior_island_total_level% shows that level, and I have offset: true on my schematics menu config.
![image](https://user-images.githubusercontent.com/36940599/105645022-da35a500-5e77-11eb-8203-2d4a55cd9bb5.png) so I think that superiorskyblock2 placeholders for levels are not being updated on /is level (indeed does not updates after island creation as the 1. problem)

SuperiorSkyBlock2 Version: 1.5.2
Server version: tacospigot 1.8.8

**Comment by OmerBenGera** [comment]
Did you do what I told you to do?

**Comment by J4im3x0** [comment]
> Did you do what I told you to do?

I used offset: true
```yml
  '!':
    schematic: 'bosque-chico'
    required-permission: ''
    biome: TAIGA
    offset: true
    access:
      type: SAPLING
      data: 1
      name: '&fIsla Bosque Pequeña &a(Disponible)'
      lore:
        - '&f'
        - '&fIsla pequeña tematizada como bosque.'
    no-access:
      type: SAPLING
      data: 1
      name: '&fIsla Bosque Pequeña &c(No disponible)'
      lore:
        - '&f'
        - '&fIsla pequeña tematizada como bosque.'
```
